### ISSUE TITLE
Corrección de ruta del controlador principal

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/cine-linx#3]
Revisar y corregir el conflicto existente al momento de lanzar la aplicacion en referencia a los controladores.

Adjunto error en consola.
```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'productoController' method
com.services.cinelinx.controller.ProductoController#index_confiteria()
to {GET []}: There is already 'homeController' bean method
com.services.cinelinx.controller.HomeController#index() mapped.
```

**Comment by LiesselRojas** [comment]
Se actualizó la ruta base del controlador ProductoController y se modificó la anotación @RequestMapping("") en la clase ProductoController para especificar la ruta base del controlador como "/productos". 

![Cap_110623](https://github.com/Devs-Com/cine-linx/assets/81693695/cccd0e53-3b6d-4f9c-87c4-de76cf1b237b)

**Comment by AnderMendoza** [comment]
Excelente, buen aporte! 😉
